services:
  aibasedchatbotcapstone:
    image: aibasedchatbotcapstone
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PYTHONPATH=/app
    ports:
      - 8000:8000
    env_file:
      - .env
    