version: "3.9"

services:
  aibasedchatbotcapstone:
    container_name: chatbot-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: aibasedchatbotcapstone
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
   
    